version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: bdadamas24/node-xvfb
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: xvfb-run --server-args="-screen 0 1024x768x24" npm test
